<cfsilent>
	<cfset request.jsFiles = [
		"res/js/lib/jquery-1.8.1.min.js",
		"res/js/lib/jquery.json-2.2.min.js",
		"res/js/lib/aw2-1.0.min.js",
		"res/js/lib/aw20.data-control-1.0.min.js",
		"res/js/lib/jquery-ui-1.10.2.custom.min.js",
		"res/js/lib/jqmodal.js",
		"res/js/sticky_common.js",
		"res/js/sticky_store.js"
	] />
	
	<cfset request.cssFiles = [
		"res/css/main.css",
		"res/css/jqmodal.css",
		"res/css/jquery-ui-1.10.2.custom.min.css",
		"res/css/mods/jquery-ui-slider.css"
	] />
</cfsilent>

<html>
	<head>
		<title>WP - Sticky Tracker</title>
	</head>
	<body>
