<div class="sticky-small j-sticky-note j-sticky-small j-default-hidden" style="display:none;">
	<input type="hidden" value="" class="j-sticky-mongoid" key="_id" />
	<input type="hidden" value="" class="j-sticky-percent-complete" key="percent_complete" />
	<input type="hidden" value="" class="j-sticky-dev-stage" key="dev_stage" />
	<input type="hidden" value="" class="j-sticky-desc" key="desc" />
	<input type="hidden" value="" class="j-sticky-notes" key="notes" />
	<input type="hidden" value="" class="" key="ticket_number" />


	<div class="sticky-handle j-sticky-handle"></div>
	<div class="sticky-field sticky-title j-sticky-title" contenteditable="true" key="title"></div>
	<div class="sticky-field j-sticky-user" contenteditable="true" key="user"></div>
	<div class="sticky-field" contenteditable="true" key="goal_dt"></div>
	<div class="sticky-slider j-sticky-slider"></div>
	<!---
	<button class="btn sticky-more-info j-sticky-more-info ui-icon-pencil">Details</button>
	--->
	<div class="btn sticky-more-info j-sticky-more-info ui-icon-pencil"></div>
	
	<div class="btn sticky-note-remove j-sticky-remove ui-icon-close"></div>
	<!---
	<img src="res/img/btn_closelabel.png" class="j-sticky-remove sticky-note-remove" />
--->
</div> <!--- /.j-sticky-note --->