<!--- hidden sticky note used for templating purposes --->
<div class="j-sticky-note j-default-hidden" style="display:none;">
	<div class="sticky-handle j-sticky-handle"></div>
	<div class="sticky-field j-sticky-title" contenteditable="true" key="task_title"></div>
	<div class="sticky-field sticky-desc j-sticky-desc" contenteditable="true" key="task_desc"></div>
	<div class="sticky-field" contenteditable="true" key="task_goaltime"></div>
	
	<img src="res/img/btn_closelabel.png" class="j-sticky-remove sticky-note-remove" />
</div> <!--- /.j-sticky-note --->